
export const GET_TRANSACTION_REQUEST = "GET_TRANSACTION_REQUEST";
export const GET_TRANSACTION_SUCCESS = "GET_TRANSACTION_SUCCESS";
export const GET_TRANSACTION_ERROR = "GET_TRANSACTION_ERROR";

export const GET_WALLET_AMOUNT_REQUEST = "GET_WALLET_AMOUNT_REQUEST";
export const GET_WALLET_AMOUNT_SUCCESS = "GET_WALLET_AMOUNT_SUCCESS";
export const GET_WALLET_AMOUNT_ERROR = "GET_WALLET_AMOUNT_ERROR";

export const CREATE_TRANSACTION_REQUEST = "CREATE_TRANSACTION_REQUEST";
export const CREATE_TRANSACTION_SUCCESS = "CREATE_TRANSACTION_SUCCESS";
export const CREATE_TRANSACTION_ERROR = "CREATE_TRANSACTION_ERROR";

export const REMOVE_TRANSACTION_REQUEST = "REMOVE_TRANSACTION_REQUEST";
export const REMOVE_TRANSACTION_SUCCESS = "REMOVE_TRANSACTION_SUCCESS";
export const REMOVE_TRANSACTION_ERROR = "REMOVE_TRANSACTION_ERROR";

export const UPDATE_TRANSACTION_REQUEST = "UPDATE_TRANSACTION_REQUEST";
export const UPDATE_TRANSACTION_SUCCESS = "UPDATE_TRANSACTION_SUCCESS";
export const UPDATE_TRANSACTION_ERROR = "UPDATE_TRANSACTION_ERROR";

export const GET_WALLET = "GET_WALLET";
export const GET_WALLET_SUCCESS = "GET_WALLET_SUCCESS";
export const GET_WALLET_FAIL = "GET_WALLET_FAIL";

export const UPDATE_WALLET = "UPDATE_WALLET";
export const UPDATE_WALLET_SUCCESS = "UPDATE_WALLET_SUCCESS";
export const UPDATE_WALLET_FAIL = "UPDATE_WALLET_FAIL";

export const GET_PAYMENT_METHOD = "GET_PAYMENT_METHOD";
export const GET_PAYMENT_METHOD_SUCCESS = "GET_PAYMENT_METHOD_SUCCESS";
export const GET_PAYMENT_METHOD_FAIL = "GET_PAYMENT_METHOD_FAIL";

export const GET_PAYMENT_DETAIL = "GET_PAYMENT_DETAIL";
export const GET_PAYMENT_DETAIL_SUCCESS = "GET_PAYMENT_DETAIL_SUCCESS";
export const GET_PAYMENT_DETAIL_FAIL = "GET_PAYMENT_DETAIL_FAIL";

export const ADD_PAYMENT_DETAIL = "ADD_PAYMENT_DETAIL";
export const ADD_PAYMENT_DETAIL_SUCCESS = "ADD_PAYMENT_DETAIL_SUCCESS";
export const ADD_PAYMENT_DETAIL_FAIL = "ADD_PAYMENT_DETAIL_FAIL";

export const UPDATE_PAYMENT_DETAIL = "UPDATE_PAYMENT_DETAIL";
export const UPDATE_PAYMENT_DETAIL_SUCCESS = "UPDATE_PAYMENT_DETAIL_SUCCESS";
export const UPDATE_PAYMENT_DETAIL_FAIL = "UPDATE_PAYMENT_DETAIL_FAIL";

export const FETCH_ALL_PAYMENT_DETAILS = "FETCH_ALL_PAYMENT_DETAILS";
export const FETCH_ALL_PAYMENT_DETAILS_SUCCESS = "FETCH_ALL_PAYMENT_DETAILS_SUCCESS";
export const FETCH_ALL_PAYMENT_DETAILS_FAIL = "FETCH_ALL_PAYMENT_DETAILS_FAIL";

export const DELETE_PAYMENT_DETAILS = "DELETE_PAYMENT_DETAILS";
export const DELETE_PAYMENT_DETAILS_SUCCESS = "DELETE_PAYMENT_DETAILS_SUCCESS";
export const DELETE_PAYMENT_DETAILS_FAIL = "DELETE_PAYMENT_DETAILS_FAIL";

export const FETCH_ALL_SECURE_PAYMENT_DETAILS = "FETCH_ALL_SECURE_PAYMENT_DETAILS";
export const FETCH_ALL_SECURE_PAYMENT_DETAILS_SUCCESS = "FETCH_ALL_SECURE_PAYMENT_DETAILS_SUCCESS";
export const FETCH_ALL_SECURE_PAYMENT_DETAILS_FAIL = "FETCH_ALL_SECURE_PAYMENT_DETAILS_FAIL";