// CRUD INFLUENCER

export const GET_INFLUENCERS = "GET_INFLUENCERS";
export const GET_INFLUENCERS_SUCCESS = "GET_INFLUENCERS_SUCCESS";
export const GET_INFLUENCERS_FAIL = "GET_INFLUENCERS_FAIL";

// ADD INFLUENCER

export const ADD_INFLUENCER = "ADD_INFLUENCER";
export const ADD_INFLUENCER_SUCCESS = "ADD_INFLUENCER_SUCCESS";
export const ADD_INFLUENCER_FAIL = "ADD_INFLUENCER_FAIL";

// UPDATE INFLUENCER

export const UPDATE_INFLUENCER = "UPDATE_INFLUENCER";
export const UPDATE_INFLUENCER_SUCCESS = "UPDATE_INFLUENCER_SUCCESS";
export const UPDATE_INFLUENCER_FAIL = "UPDATE_INFLUENCER_FAIL";

// DELETE INFLUENCER

export const DELETE_INFLUENCER = "DELETE_INFLUENCER";
export const DELETE_INFLUENCER_SUCCESS = "DELETE_INFLUENCER_SUCCESS";
export const DELETE_INFLUENCER_FAIL = "DELETE_INFLUENCER_FAIL";

// GET SPECIFIC INFLUENCER

export const GET_SPECIFIC_INFLUENCER = "GET_SPECIFIC_INFLUENCER";
export const GET_SPECIFIC_INFLUENCER_SUCCESS = "GET_SPECIFIC_INFLUENCER_SUCCESS";
export const GET_SPECIFIC_INFLUENCER_FAIL = "GET_SPECIFIC_INFLUENCER_FAIL";