export const GET_PUBLICATION_REQUEST = "GET_PUBLICATION_REQUEST";
export const GET_PUBLICATION_SUCCESS = "GET_PUBLICATION_SUCCESS";
export const GET_PUBLICATION_ERROR = "GET_PUBLICATION_ERROR";

export const CREATE_PUBLICATION_REQUEST = "CREATE_PUBLICATION_REQUEST";
export const CREATE_PUBLICATION_SUCCESS = "CREATE_PUBLICATION_SUCCESS";
export const CREATE_PUBLICATION_ERROR = "CREATE_PUBLICATION_ERROR";

export const UPDATE_PUBLICATION_REQUEST = "UPDATE_PUBLICATION_REQUEST";
export const UPDATE_PUBLICATION_SUCCESS = "UPDATE_PUBLICATION_SUCCESS";
export const UPDATE_PUBLICATION_ERROR = "UPDATE_PUBLICATION_ERROR";

export const DELETE_PUBLICATION_REQUEST = "DELETE_PUBLICATION_REQUEST";
export const DELETE_PUBLICATION_SUCCESS = "DELETE_PUBLICATION_SUCCESS";
export const DELETE_PUBLICATION_ERROR = "DELETE_PUBLICATION_ERROR";

export const UPDATE_PUBLICATION_STATUS_REQUEST = "UPDATE_PUBLICATION_STATUS_REQUEST";
export const UPDATE_PUBLICATION_STATUS_SUCCESS = "UPDATE_PUBLICATION_STATUS_SUCCESS";
export const UPDATE_PUBLICATION_STATUS_ERROR = "UPDATE_PUBLICATION_STATUS_ERROR";
