export const GET_TICKET_NOTIFICATION = "GET_TICKET_NOTIFICATION";
export const GET_TICKET_NOTIFICATION_SUCCESS = "GET_TICKET_NOTIFICATION_SUCCESS";
export const GET_TICKET_NOTIFICATION_FAIL = "GET_TICKET_NOTIFICATION_FAIL";

export const CREATE_TICKET_NOTIFICATION = "CREATE_TICKET_NOTIFICATION";
export const CREATE_TICKET_NOTIFICATION_SUCCESS = "CREATE_TICKET_NOTIFICATION_SUCCESS";
export const CREATE_TICKET_NOTIFICATION_FAIL = "CREATE_TICKET_NOTIFICATION_FAIL";

export const UPDATE_TICKET_NOTIFICATION = "UPDATE_TICKET_NOTIFICATION";
export const UPDATE_TICKET_NOTIFICATION_SUCCESS = "UPDATE_TICKET_NOTIFICATION_SUCCESS";
export const UPDATE_TICKET_NOTIFICATION_FAIL = "UPDATE_TICKET_NOTIFICATION_FAIL";

export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS";
export const CREATE_NOTIFICATION_FAIL = "CREATE_NOTIFICATION_FAIL";

export const FETCH_UNREAD_NOTIFICATIONS = "FETCH_UNREAD_NOTIFICATIONS";
export const FETCH_UNREAD_NOTIFICATIONS_SUCCESS = "FETCH_UNREAD_NOTIFICATIONS_SUCCESS";
export const FETCH_UNREAD_NOTIFICATIONS_FAIL = "FETCH_UNREAD_NOTIFICATIONS_FAIL";

export const MARK_NOTIFICATION_AS_READ = "MARK_NOTIFICATION_AS_READ";
export const MARK_NOTIFICATION_AS_READ_SUCCESS = "MARK_NOTIFICATION_AS_READ_SUCCESS";
export const MARK_NOTIFICATION_AS_READ_FAIL = "MARK_NOTIFICATION_AS_READ_FAIL";
