// // CRUD INFLUENCER

// export const GET_CLIENT = "GET_CLIENT";
// export const GET_CLIENT_SUCCESS = "GET_CLIENT_SUCCESS";
// export const GET_CLIENT_FAIL = "GET_CLIENT_FAIL";

// ADD INFLUENCER

export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_FAIL = "ADD_CLIENT_FAIL";

// // UPDATE INFLUENCER

// export const UPDATE_CLIENT = "UPDATE_CLIENT";
// export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
// export const UPDATE_CLIENT_FAIL = "UPDATE_CLIENT_FAIL";

// // DELETE INFLUENCER

// export const DELETE_CLIENT = "DELETE_CLIENT";
// export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
// export const DELETE_CLIENT_FAIL = "DELETE_CLIENT_FAIL";

// // GET SPECIFIC INFLUENCER

// export const GET_SPECIFIC_CLIENT = "GET_SPECIFIC_CLIENT";
// export const GET_SPECIFIC_CLIENT_SUCCESS = "GET_SPECIFIC_CLIENT_SUCCESS";
// export const GET_SPECIFIC_CLIENT_FAIL = "GET_SPECIFIC_CLIENT_FAIL";
