export const GET_TIKTOK_USER_DATA = "GET_TIKTOK_USER_DATA";
export const GET_TIKTOK_USER_DATA_SUCCESS = "GET_TIKTOK_USER_DATA_SUCCESS";
export const GET_TIKTOK_USER_DATA_FAIL = "GET_TIKTOK_USER_DATA_FAIL";

export const GET_MONTHLY_PERFORMANCE_ANALYTICS = "GET_MONTHLY_PERFORMANCE_ANALYTICS";
export const GET_MONTHLY_PERFORMANCE_ANALYTICS_SUCCESS = "GET_MONTHLY_PERFORMANCE_ANALYTICS_SUCCESS";
export const GET_MONTHLY_PERFORMANCE_ANALYTICS_FAIL = "GET_MONTHLY_PERFORMANCE_ANALYTICS_FAIL";

export const GET_TICKET_ENGAGEMENT_STATISTICS = "GET_TICKET_ENGAGEMENT_STATISTICS";
export const GET_TICKET_ENGAGEMENT_STATISTICS_SUCCESS = "GET_TICKET_ENGAGEMENT_STATISTICS_SUCCESS";
export const GET_TICKET_ENGAGEMENT_STATISTICS_FAIL = "GET_TICKET_ENGAGEMENT_STATISTICS_FAIL";
