// CRUD INFLUENCER

export const GET_INFLUENCERS = "GET_INFLUENCERS";
export const GET_INFLUENCERS_SUCCESS = "GET_INFLUENCERS_SUCCESS";
export const GET_INFLUENCERS_FAIL = "GET_INFLUENCERS_FAIL";

// ADD INFLUENCER

export const ADD_INFLUENCER = "ADD_INFLUENCER";
export const ADD_INFLUENCER_SUCCESS = "ADD_INFLUENCER_SUCCESS";
export const ADD_INFLUENCER_FAIL = "ADD_INFLUENCER_FAIL";

// UPDATE INFLUENCER

export const UPDATE_INFLUENCER = "UPDATE_INFLUENCER";
export const UPDATE_INFLUENCER_SUCCESS = "UPDATE_INFLUENCER_SUCCESS";
export const UPDATE_INFLUENCER_FAIL = "UPDATE_INFLUENCER_FAIL";
