// CRUD INFLUENCER

export const GET_INFLUENCERS = "GET_INFLUENCERS";
export const GET_INFLUENCERS_SUCCESS = "GET_INFLUENCERS_SUCCESS";
export const GET_INFLUENCERS_FAIL = "GET_INFLUENCERS_FAIL";

// ADD INFLUENCER

export const ADD_INFLUENCER = "ADD_INFLUENCER";
export const ADD_INFLUENCER_SUCCESS = "ADD_INFLUENCER_SUCCESS";
export const ADD_INFLUENCER_FAIL = "ADD_INFLUENCER_FAIL";

// UPDATE INFLUENCER

export const UPDATE_INFLUENCER = "UPDATE_INFLUENCER";
export const UPDATE_INFLUENCER_SUCCESS = "UPDATE_INFLUENCER_SUCCESS";
export const UPDATE_INFLUENCER_FAIL = "UPDATE_INFLUENCER_FAIL";

export const GET_INFLUENCER_PROFILE = "GET_INFLUENCER_PROFILE";
export const GET_INFLUENCER_PROFILE_SUCCESS = "GET_INFLUENCER_PROFILE_SUCCESS";
export const GET_INFLUENCER_PROFILE_FAIL = "GET_INFLUENCER_PROFILE_FAIL";

export const GET_INFLUENCER_BASIC_DATA = "GET_INFLUENCER_BASIC_DATA";
export const GET_INFLUENCER_BASIC_DATA_SUCCESS = "GET_INFLUENCER_BASIC_DATA_SUCCESS";
export const GET_INFLUENCER_BASIC_DATA_FAIL = "GET_INFLUENCER_BASIC_DATA_FAIL";

export const GET_INFLUENCER_POST_STATISTICS = "GET_INFLUENCER_POST_STATISTICS";
export const GET_INFLUENCER_POST_STATISTICS_SUCCESS = "GET_INFLUENCER_POST_STATISTICS_SUCCESS";
export const GET_INFLUENCER_POST_STATISTICS_FAIL = "GET_INFLUENCER_POST_STATISTICS_FAIL";

export const GET_INFLUENCER_MONTHLY_STATISTICS = "GET_INFLUENCER_MONTHLY_STATISTICS";
export const GET_INFLUENCER_MONTHLY_STATISTICS_SUCCESS = "GET_INFLUENCER_MONTHLY_STATISTICS_SUCCESS";
export const GET_INFLUENCER_MONTHLY_STATISTICS_FAIL = "GET_INFLUENCER_MONTHLY_STATISTICS_FAIL";

export const GET_INFLUENCER_DEMOGRAPHIC_DATA = "GET_INFLUENCER_DEMOGRAPHIC_DATA";
export const GET_INFLUENCER_DEMOGRAPHIC_DATA_SUCCESS = "GET_INFLUENCER_DEMOGRAPHIC_DATA_SUCCESS";
export const GET_INFLUENCER_DEMOGRAPHIC_DATA_FAIL = "GET_INFLUENCER_DEMOGRAPHIC_DATA_FAIL";

export const GET_INFLUENCER_PUBLICATION_DATA = "GET_INFLUENCER_PUBLICATION_DATA";
export const GET_INFLUENCER_PUBLICATION_DATA_SUCCESS = "GET_INFLUENCER_PUBLICATION_DATA_SUCCESS";
export const GET_INFLUENCER_PUBLICATION_DATA_FAIL = "GET_INFLUENCER_PUBLICATION_DATA_FAIL";

export const GET_INFLUENCER_MEDIA_DATA = "GET_INFLUENCER_MEDIA_DATA";
export const GET_INFLUENCER_MEDIA_DATA_SUCCESS = "GET_INFLUENCER_MEDIA_DATA_SUCCESS";
export const GET_INFLUENCER_MEDIA_DATA_FAIL = "GET_INFLUENCER_MEDIA_DATA_FAIL";
