// // CRUD BRAND

export const GET_BRAND = "GET_BRAND";
export const GET_BRAND_SUCCESS = "GET_BRAND_SUCCESS";
export const GET_BRAND_FAIL = "GET_BRAND_FAIL";

export const GET_BRAND_LIST = "GET_BRAND_LIST";
export const GET_BRAND_LIST_SUCCESS = "GET_BRAND_LIST_SUCCESS";
export const GET_BRAND_LIST_FAIL = "GET_BRAND_LIST_FAIL";

// ADD INFLUENCER

export const ADD_BRAND = "ADD_BRAND";
export const ADD_BRAND_SUCCESS = "ADD_BRAND_SUCCESS";
export const ADD_BRAND_FAIL = "ADD_BRAND_FAIL";

// UPDATE INFLUENCER

export const UPDATE_BRAND = "UPDATE_BRAND";
export const UPDATE_BRAND_SUCCESS = "UPDATE_BRAND_SUCCESS";
export const UPDATE_BRAND_FAIL = "UPDATE_BRAND_FAIL";

// Brand Statistics
export const GET_BRAND_STATISTICS = "GET_BRAND_STATISTICS";
export const GET_BRAND_STATISTICS_SUCCESS = "GET_BRAND_STATISTICS_SUCCESS";
export const GET_BRAND_STATISTICS_FAIL = "GET_BRAND_STATISTICS_FAIL";

// Opportunity Statistics
export const GET_OPPORTUNITY_STATISTICS = "GET_OPPORTUNITY_STATISTICS";
export const GET_OPPORTUNITY_STATISTICS_SUCCESS = "GET_OPPORTUNITY_STATISTICS_SUCCESS";
export const GET_OPPORTUNITY_STATISTICS_FAIL = "GET_OPPORTUNITY_STATISTICS_FAIL";

// Influencers Statistics
export const GET_INFLUENCER_STATISTICS = "GET_INFLUENCER_STATISTICS";
export const GET_INFLUENCER_STATISTICS_SUCCESS = "GET_INFLUENCER_STATISTICS_SUCCESS";
export const GET_INFLUENCER_STATISTICS_FAIL = "GET_INFLUENCER_STATISTICS_FAIL";

// Influencer Statistics by Platform
export const GET_INFLUENCER_STATISTICS_BY_PLATFORM = "GET_INFLUENCER_STATISTICS_BY_PLATFORM";
export const GET_INFLUENCER_STATISTICS_BY_PLATFORM_SUCCESS = "GET_INFLUENCER_STATISTICS_BY_PLATFORM_SUCCESS";
export const GET_INFLUENCER_STATISTICS_BY_PLATFORM_FAIL = "GET_INFLUENCER_STATISTICS_BY_PLATFORM_FAIL";

// Influencer Statistics by Country
export const GET_INFLUENCER_STATISTICS_BY_COUNTRY = "GET_INFLUENCER_STATISTICS_BY_COUNTRY";
export const GET_INFLUENCER_STATISTICS_BY_COUNTRY_SUCCESS = "GET_INFLUENCER_STATISTICS_BY_COUNTRY_SUCCESS";
export const GET_INFLUENCER_STATISTICS_BY_COUNTRY_FAIL = "GET_INFLUENCER_STATISTICS_BY_COUNTRY_FAIL";

// Publications by Brand
export const GET_ALL_PUBLICATIONS_BY_BRAND = "GET_ALL_PUBLICATIONS_BY_BRAND";
export const GET_ALL_PUBLICATIONS_BY_BRAND_SUCCESS = "GET_ALL_PUBLICATIONS_BY_BRAND_SUCCESS";
export const GET_ALL_PUBLICATIONS_BY_BRAND_FAIL = "GET_ALL_PUBLICATIONS_BY_BRAND_FAIL";
