// GET ALL OPPORTUNITY
export const GET_OPPORTUNITY_REQUEST = "GET_OPPORTUNITY_REQUEST";
export const GET_OPPORTUNITY_SUCCESS = "GET_OPPORTUNITY_SUCCESS";
export const GET_OPPORTUNITY_ERROR = "GET_OPPORTUNITY_ERROR";

// CREATE OPPORTUNITY
export const CREATE_OPPORTUNITY_REQUEST = "CREATE_OPPORTUNITY_REQUEST";
export const CREATE_OPPORTUNITY_SUCCESS = "CREATE_OPPORTUNITY_SUCCESS";
export const CREATE_OPPORTUNITY_ERROR = "CREATE_OPPORTUNITY_ERROR";

// DELETE OPPORTUNITY
export const DELETE_OPPORTUNITY_REQUEST = "DELETE_OPPORTUNITY_REQUEST";
export const DELETE_OPPORTUNITY_SUCCESS = "DELETE_OPPORTUNITY_SUCCESS";
export const DELETE_OPPORTUNITY_ERROR = "DELETE_OPPORTUNITY_ERROR";

// UPDATE OPPORTUNITY
export const UPDATE_OPPORTUNITY_REQUEST = "UPDATE_OPPORTUNITY_REQUEST";
export const UPDATE_OPPORTUNITY_SUCCESS = "UPDATE_OPPORTUNITY_SUCCESS";
export const UPDATE_OPPORTUNITY_ERROR = "UPDATE_OPPORTUNITY_ERROR";
