// GET ALL OPPORTUNITY
export const GET_OPPORTUNITY_REQUEST = "GET_OPPORTUNITY_REQUEST";
export const GET_OPPORTUNITY_SUCCESS = "GET_OPPORTUNITY_SUCCESS";
export const GET_OPPORTUNITY_ERROR = "GET_OPPORTUNITY_ERROR";

// CREATE OPPORTUNITY
export const CREATE_OPPORTUNITY_REQUEST = "CREATE_OPPORTUNITY_REQUEST";
export const CREATE_OPPORTUNITY_SUCCESS = "CREATE_OPPORTUNITY_SUCCESS";
export const CREATE_OPPORTUNITY_ERROR = "CREATE_OPPORTUNITY_ERROR";

// DELETE OPPORTUNITY
export const DELETE_OPPORTUNITY_REQUEST = "DELETE_OPPORTUNITY_REQUEST";
export const DELETE_OPPORTUNITY_SUCCESS = "DELETE_OPPORTUNITY_SUCCESS";
export const DELETE_OPPORTUNITY_ERROR = "DELETE_OPPORTUNITY_ERROR";

// UPDATE OPPORTUNITY
export const UPDATE_OPPORTUNITY_REQUEST = "UPDATE_OPPORTUNITY_REQUEST";
export const UPDATE_OPPORTUNITY_SUCCESS = "UPDATE_OPPORTUNITY_SUCCESS";
export const UPDATE_OPPORTUNITY_ERROR = "UPDATE_OPPORTUNITY_ERROR";

// UPLOAD IMAGE
export const UPLOAD_OPPORTUNITY_IMAGE_REQUEST = "UPLOAD_OPPORTUNITY_IMAGE_REQUEST";
export const UPLOAD_OPPORTUNITY_IMAGE_SUCCESS = "UPLOAD_OPPORTUNITY_IMAGE_SUCCESS";
export const UPLOAD_OPPORTUNITY_IMAGE_ERROR = "UPLOAD_OPPORTUNITY_IMAGE_ERROR";

// REMOVE IMAGE
export const REMOVE_OPPORTUNITY_IMAGE_REQUEST = "REMOVE_OPPORTUNITY_IMAGE_REQUEST";
export const REMOVE_OPPORTUNITY_IMAGE_SUCCESS = "REMOVE_OPPORTUNITY_IMAGE_SUCCESS";
export const REMOVE_OPPORTUNITY_IMAGE_ERROR = "REMOVE_OPPORTUNITY_IMAGE_ERROR";

// Fetch Tickets
export const FETCH_TICKETS_REQUEST = "FETCH_TICKETS_REQUEST";
export const FETCH_TICKETS_SUCCESS = "FETCH_TICKETS_SUCCESS";
export const FETCH_TICKETS_ERROR = "FETCH_TICKETS_ERROR";

// Create Ticket
export const CREATE_TICKET_REQUEST = "CREATE_TICKET_REQUEST";
export const CREATE_TICKET_SUCCESS = "CREATE_TICKET_SUCCESS";
export const CREATE_TICKET_ERROR = "CREATE_TICKET_ERROR";

export const UPDATE_TICKET_REQUEST = "UPDATE_TICKET_REQUEST";
export const UPDATE_TICKET_SUCCESS = "UPDATE_TICKET_SUCCESS";
export const UPDATE_TICKET_ERROR = "UPDATE_TICKET_ERROR";
